<?php

/**
 * ProcessWire Page Edit Process
 *
 * Provides the UI for editing a page
 * 
 * For more details about how Process modules work, please see: 
 * /wire/core/Process.php 
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2011 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessPageEdit extends Process {

	protected $form; 
	protected $page; 
	protected $parent; 
	protected $user; 
	protected $id; 
	protected $redirectUrl;
	protected $pageClass; 
	protected $isTrash; 
	protected $allowedTemplates = null; // cache
	protected $isPost = false;
	protected $useSettings = true; 
	protected $useChildren = true; 
	protected $useView = true; 

	public static function getModuleInfo() {
		return array(
			'title' => 'Page Edit',          
			'summary' => 'Edit a Page', 
			'version' => 101, 
			'permanent' => true, 
			'permission' => 'page-edit',
			);
	}

	/**
	 * Initialize the page editor by loading the requested page and any dependencies
	 *
	 */
	public function init() {

		if(isset($_POST['id'])) $this->id = (int) $_POST['id']; 
			else if(isset($_GET['id'])) $this->id = (int) $_GET['id']; 

		if(!$this->id) throw new Wire404Exception("PageEdit requires a Page ID");

		$this->user = $this->fuel('user');
		$this->page = $this->pages->get($this->id); 
		if($this->page instanceof NullPage) throw new WireException("Page does not exist"); 
		$this->pageClass = $this->page->className();
		$this->page->setOutputFormatting(false); 
		$this->parent = $this->pages->get($this->page->parent_id); 
		$this->isTrash = $this->page->isTrash;

		if(!$this->page) throw new Wire404Exception("Unable to load page {$this->id}"); 
		if(!$this->page->editable()) throw new WirePermissionException("You don't have access to edit this page"); 

		// determine if we're going to be dealing with a save/post request
		$this->isPost = ($this->input->post->id > 0 && (((int) $this->input->post->id) === $this->page->id)) || $this->config->ajax && (count($_POST) || isset($_SERVER['HTTP_X_FIELDNAME'])); 

		// after confirming that the page is editable, if the current user is the one that created the page 
		// then temporarily give both the page and the user the special "owner" role 

		if($this->page->createdUserID == $this->user->id) {
			// TODO for new user system, old part commented out below but kept for reference:
			// $ownerRole = $this->roles->get(Role::ownerRoleID); 
			// $this->page->addRole($ownerRole); 
			// $this->user->addRole($ownerRole); 
		}

		if(!$this->isPost) { 
			$this->setupHeadline();
			$this->setupBreadcrumbs();
		}

		parent::init();

		if(!$this->isPost) $this->modules->get('JqueryWireTabs'); 
	}

	/**
	 * Execute the Page Edit process by building the form and checking if it was submitted
	 *
	 */
	public function ___execute() {

		if($this->config->ajax && (isset($_SERVER['HTTP_X_FIELDNAME']) || count($_POST))) return $this->ajaxSave();

		$this->form = $this->buildForm();
		$this->form->setTrackChanges();

		if($this->isPost && count($_POST)) $this->processSave();

		if($this->page->is(Page::statusLocked)) {
			if($this->user->hasPermission('page-lock', $this->page)) {
				$this->message("Note that this page is locked and no changes will be accepted unless first unlocked."); 
			} else {
				$this->error("This page is locked for edits and you may not make changes to this page."); 
			}
		}

		if($this->page->is(Page::statusUnpublished)) {
			$this->message("This page is not published. You will have to publish this page before it is visible on the site."); 
		}

		return $this->renderEdit();
	}


	/**
	 * Render the Page Edit form
	 *
	 */
	protected function renderEdit() {
		$class = '';
		$out = "<p id='PageIDIndicator' class='$class'>" . ($this->page->id ? $this->page->id : "New") . "</p>";
		if($this->form->description) { 
			$out .= "<h2>" . $this->form->description . "</h2>";
			$this->form->description = '';
		}
		$out .= $this->form->render();
		return $out; 
	}

	/**
	 * Save a submitted Page Edit form 
	 *
	 */
	protected function processSave() {

		if($this->page->is(Page::statusLocked)) {

			if(!$this->user->hasPermission('page-lock', $this->page) || (!empty($_POST['status']) && in_array(Page::statusLocked, $_POST['status']))) {
				$this->error("Your changes were not saved because this page is locked"); 
			}

		} else if($this->input->post->submit_delete) {

			if($this->input->post->delete_page) $this->deletePage();

		} else {

			$this->processInput($this->form); 

			foreach($this->page->getChanges() as $change) {
				$this->message("Change: $change");
			}

			$formErrors = 0; 
			foreach($this->notices as $notice) {
				if($notice instanceof NoticeError) $formErrors++; 
			}

			if($this->input->post->submit_publish || $this->input->post->submit_save) {

				try {
					if($this->input->post->submit_publish && $this->page->is(Page::statusUnpublished)) {
						$this->page->removeStatus(Page::statusUnpublished);
						$this->message("Published Page: {$this->page->url}"); 
					} else {
						$this->message("Saved Page: {$this->page->url}"); 
					}

					$this->page->save();

				} catch(Exception $e) {
					$this->error($e->getMessage()); 
				}
			}
		}

		if(!$this->redirectUrl) $this->redirectUrl = "./?id={$this->page->id}";
		if($this->input->get->modal) $this->redirectUrl .= "&modal=1";
		$this->session->redirect($this->redirectUrl); 
	}	

	/**
	 * Build the form used for Page Edits
	 *
	 */
	protected function ___buildForm() {

		$form = $this->modules->get('InputfieldForm');

		$fields = $this->page->getInputfields();
		$fields->attr('id', $this->className() . 'Content'); 
		$fields->attr('title', 'Content'); 

		$form->attr('id+name', 'ProcessPageEdit'); 
		$form->attr('action', './?id=' . $this->id . ($this->input->get->modal ? "&modal=1" : '')); 
		$form->attr('method', 'post'); 
		$form->attr('enctype', 'multipart/form-data'); 
		$form->attr('class', 'template_' . $this->page->template . ' class_' . $this->page->className); 
		$form->attr('autocomplete', 'off'); 

		if($this->page->template->nameContentTab) {
			// name
			$field = $this->modules->get('InputfieldPageName');
			$field->attr('value', $this->page->name); 
			$field->required = true; 
			if(!$this->page->editable('name')) $field->attr('disabled', 'disabled'); 
			if($this->page->parent) $field->parentPage = $this->page->parent;
			$fields->prepend($field); 
		}

		$form->append($fields); 

		if($this->page->addable() || $this->page->numChildren) $form->append($this->buildFormChildren()); 
		if(!$this->page->template->noSettings) $form->append($this->buildFormSettings()); 
		if($this->isTrash) $form->description = "This page is in the Trash"; 
		if($this->page->deleteable()) $form->append($this->buildFormDelete());
		if($this->page->viewable() && !$this->input->get->modal) $form->append($this->buildFormView()); 

		if($this->page->is(Page::statusUnpublished)) {

			if(!$form->description) $form->description = "This page is currently unpublished";

			$field2 = $this->modules->get('InputfieldSubmit'); 
			$field2->attr('name', 'submit_save'); 
			$field2->attr('id', 'submit_save_unpublished'); 
			$field2->class .= ' ui-priority-secondary'; 
			$field2->attr('value', 'Save + Keep Unpublished'); 

			$saveName = 'submit_publish';
			$saveLabel = "Publish " . $this->pageClass; 
		} else {
			$field2 = null;
			$saveName = 'submit_save';
			$saveLabel = "Save " . $this->pageClass; 
		}

		$field = $this->modules->get('InputfieldSubmit');
		$field->attr('id+name', $saveName); 
		$field->attr('value', $saveLabel); 
		$form->append($field); 

		if($field2) $form->append($field2); 

		if($this->page->className() == 'Page') {
			$field = $this->modules->get('InputfieldSubmit');
			$field->attr('name', $saveName); 
			$field->attr('id', 'submit_save_top'); 
			$field->attr('value', $saveLabel); 
			$form->append($field); 
		}

		$field = $this->modules->get('InputfieldHidden');
		$field->attr('name', 'id');
		$field->attr('value', $this->page->id); 
		$form->append($field); 

		return $form; 
	}

	/**
	 * Build the 'children' tab on the Page Edit form
 	 *
	 */
	protected function ___buildFormChildren() {

		$wrapper = new InputfieldWrapper();
		$wrapper->attr('id', $this->className() . 'Children'); 
		$title = 'Children'; 
		if($this->page->numChildren) $title = "<em>$title</em>";
		$wrapper->attr('title', $title); 

		if(!$this->isPost) { 

			$pageListParent = $this->page ? $this->page : $this->parent; 
			if($pageListParent->numChildren) { 
				$pageList = $this->modules->get('ProcessPageList'); 
				$pageList->set('id', $pageListParent->id); 
				$pageList->set('showRootPage', false); 
			} else $pageList = null;

			$field = $this->modules->get("InputfieldMarkup"); 
			$field->label = "Children / Subpages";
			if($pageList) $field->value = $pageList->execute();
				else $field->description = "There are currently no children/subpages below this page.";

			if($this->page->addable()) { 
				$button = $this->modules->get("InputfieldButton"); 
				$button->attr('id+name', 'AddPageBtn'); 
				$button->attr('value', "Add New Page Here");
				$button->attr('href', "../add/?parent_id={$this->page->id}" . ($this->input->get->modal ? "&modal=1" : ''));
				$field->append($button);
			}
			$wrapper->append($field); 
		}


		if($this->user->hasPermission('page-sort', $this->page)) { 		
			$fieldset = $this->modules->get("InputfieldFieldset"); 
			$fieldset->collapsed = Inputfield::collapsedYes; 
			$fieldset->label = "Sort Settings";
			$fieldset->description = '' . 
				"If you want all current and future children to automatically sort by a specific field, select the field below " . 
				"and optionally check the 'reverse' checkbox to make the sort descending. Leave the sort field blank if you want " . 
				"to be able to drag-n-drop to your own order.";

			$field = $this->modules->get('InputfieldSelect');
			$field->name = 'sortfield'; 
			$field->value = ltrim($this->page->sortfield, '-'); 
			$field->label = 'Sort field';

			$options = array(
				'name' => 'name', 
				'status' => 'status', 
				'modified' => 'modified', 
				'created' => 'created', 
				); 

			$field->addOption('sort', 'None'); 
			$field->addOption('Native Fields', $options); // optgroup

			$customOptions = array();

			foreach($this->fields as $f) {
				if(!($f->flags & Field::flagAutojoin)) continue; 
				$customOptions[$f->name] = $f->name; 
			}

			ksort($customOptions); 
			$field->addOption('Custom Fields', $customOptions); // optgroup
			$fieldset->append($field); 

			$f = $this->modules->get('InputfieldCheckbox');
			$f->value = 1; 
			$f->attr('id+name', 'sortfield_reverse'); 
			$f->label = 'Reverse sort direction?'; 
			if(substr($this->page->sortfield, 0, 1) == '-') $f->attr('checked', 'checked'); 

			$fieldset->append($f); 
			$wrapper->append($fieldset); 
		}

		return $wrapper;
	}

	/**
	 * Build the 'settings' tab on the Page Edit form
	 *
	 */
	protected function ___buildFormSettings() {

		$wrapper = new InputfieldWrapper();
		$wrapper->attr('id', $this->className() . 'Settings'); 
		$wrapper->attr('title', 'Settings'); 

		if($this->page->id > 1) {

			// name
			if(!$this->page->template->nameContentTab) {
				$field = $this->modules->get('InputfieldPageName');
				$field->attr('value', $this->page->name); 
				if($field->value && !$this->page->editable('name')) $field->attr('disabled', 'disabled'); 
				$field->required = true; 
				if($this->page->parent) $field->parentPage = $this->page->parent;
				$wrapper->prepend($field); 
			}

			// parent
			if($this->page->editable('parent')) {
				$field = $this->modules->get('InputfieldPageListSelect');
				$field->label = "Parent";
				$field->attr('id+name', 'parent_id'); 
				$field->required = true; 
				$field->attr('value', $this->page->parent_id); 
				$field->parent_id = 0; 
				$wrapper->add($field); 
			}
		}

		// template
		if($this->page->editable('template')) { 
			$field = $this->modules->get('InputfieldSelect');
			$field->label = 'Template';
			$field->attr('id+name', 'template'); 
			$field->attr('value', $this->page->template->id); 
			$field->required = true; 
			foreach($this->getAllowedTemplates() as $template) $field->addOption($template->id, $template->name); 
			$wrapper->add($field); 
		}

		// status
		$wrapper->add($this->buildFormStatus()); 

		// informational sections
		if(!$this->isPost) {
			$wrapper->add($this->buildFormRoles()); 
			$wrapper->add($this->buildFormInfo()); 
		}

		return $wrapper; 
	}

	/**
	 * Build the Settings > Info fieldset on the Page Edit form
	 *
	 */
	protected function buildFormInfo() {

		$dateFormat = 'l \t\h\e jS \of F Y h:i:s A';
		$field = $this->modules->get("InputfieldMarkup"); 

		$info = "\n<p>Created by <strong>{$this->page->createdUser->name}</strong> on " . date($dateFormat, $this->page->created) . "</p>" . 
			"\n<p>Last modified by <strong>{$this->page->modifiedUser->name}</strong> on " . date($dateFormat, $this->page->modified) . "</p>";

		$field->label = 'Info';
		$field->value = $info; 
		$field->collapsed = Inputfield::collapsedYes; 
		return $field; 
	}

	/**
	 * Build the Settings > Status fieldset on the Page Edit form
	 *
	 */
	protected function buildFormStatus() {
		$status = (int) $this->page->status; 
		$field = $this->modules->get('InputfieldCheckboxes');
		$field->attr('name', 'status');
		$statuses = array(); 
		$statuses[Page::statusHidden] = "Hidden: Excluded from lists and searches";
		if($this->user->hasPermission('page-lock', $this->page)) $statuses[Page::statusLocked] = "Locked: Not editable";
		$statuses[Page::statusUnpublished] = "Unpublished: Not visible on site";
			
		if($this->config->advanced && $this->user->isSuperuser()) {
			$statuses[Page::statusSystemID] = "System: Non-deleteable and locked ID (status not removeable via API)";
			$statuses[Page::statusSystem] = "System: Non-deleteable and locked ID, name, template, parent (status not removeable via API)"; 
		}

		$value = array();
		foreach($statuses as $s => $label) {
			if($s & $status) $value[] = $s;
			$field->addOption($s, $label);
		}
		$field->attr('value', $value); 
		$field->label = "Status"; 
		return $field; 
	}

	/**
	 * Build the 'delete' tab on the Page Edit form
	 *
	 */
	protected function ___buildFormDelete() {

		$isTrash = $this->page->isTrash();
		$isRestorable = $isTrash && $this->page->parent_id == $this->config->trashPageID; 

		$wrapper = new InputfieldWrapper(); 	
		$wrapper->attr('id', $this->className() . 'Delete');
		$wrapper->attr('title', "Delete"); 

		if($this->page->deleteable()) {

			$field = $this->modules->get('InputfieldCheckbox');
			$field->attr('id+name', 'delete_page'); 
			$field->attr('value', $this->page->id); 

			if($this->isTrash || $this->page->template->noTrash) {
				$field->label = "Permanently Delete {$this->pageClass}";
				$field->description = "This will permanently delete the {$this->pageClass}. Are you sure you want to do this?"; 
			} else {
				$field->label = "Delete {$this->pageClass}";
				$field->description = "This will move this {$this->pageClass} to the Trash.";
			}
			$wrapper->append($field); 
		}

		if(count($wrapper->children())) {
			$field = $this->modules->get('InputfieldSubmit');
			$field->attr('id+name', 'submit_delete'); 
			$wrapper->append($field);
		} else {
			$wrapper->description = "This page may not be deleted at this time";
		}

		return $wrapper;
	}

	/**
	 * Build the 'view' tab on the Page Edit form
	 *
	 */ 
	protected function buildFormView($label = 'View') {
		$field = new InputfieldMarkup(); 
		$field->attr('id', $this->className() . 'View'); 
		$field->attr('title', $label); 
		$field->attr('class', 'InputfieldWrapper'); 
		$field->attr('value', "<a href='{$this->page->httpUrl}'>$label</a>"); 
		return $field;
	}

	/**
	 * Build the Settings > Roles fieldset on the Page Edit form 
	 *
	 */
	protected function buildFormRoles() {

		$field = $this->modules->get("InputfieldMarkup"); 
		$field->label = "Who can access this page?";
		$roles = $this->page->getAccessRoles();
		$editRoles = $this->page->getAccessTemplate()->editRoles;
		$addRoles = $this->page->getAccessTemplate()->addRoles; 

		$table = $this->modules->get("MarkupAdminDataTable"); 
		$table->headerRow(array('Role', 'What they can do')); 
		$table->setEncodeEntities(false);

		if(count($roles)) { 

			foreach($roles as $role) {
				$permissions = '';	
				$roleName = $role->name; 
				if($roleName == 'guest') $roleName .= " (everyone)";
				$permissions .= "View Pages\n";
				if($role->hasPermission('page-edit') && in_array($role->id, $editRoles)) { 
					foreach($role->permissions as $permission) {
						if($permission->name == 'page-view') continue;  // assumed
						if(strpos($permission->name, 'page-') !== 0) continue; 
						$permissions .= "{$permission->title}\n"; // only page-context permissions
					}
				}
				if(false !== ($key = array_search($role->id, $addRoles))) {
					$permissions .= "Add Children\n";
					unset($addRoles[$key]); 
				}
				$table->row(array($roleName, nl2br($permissions))); 
			}

		}

		if(count($addRoles)) {
			foreach($addRoles as $roleID) {
				$role = $this->fuel('roles')->get($roleID); 
				if($role->id) $table->row(array($role->name, "Add Child Pages")); 
			}
		}

		$table->row(array('superuser', 'Everything')); 

		$field->value = $table->render();

		$accessParent = $this->page->getAccessParent();
		if($accessParent === $this->page) {
			$field->notes = "Access is defined with this page's template \"{$accessParent->template}\"";	
		} else {
			$field->notes = "Access is inherited from page \"{$accessParent->path}\" and defined with template \"{$accessParent->template}\"";
		}

		return $field;
		
	}


	/**
	 * Process the input from a submitted Page Edit form, delegating to other methods where appropriate
 	 *
	 */
	protected function ___processInput(Inputfield $form, $level = 0) {

		static $skipFields = array(
			'sortfield_reverse', 
			'submit_publish', 
			'submit_save',
			);

		if(!$level) $form->processInput($this->input->post);

		foreach($form as $inputfield) {

			$name = $inputfield->attr('name'); 

			if(in_array($name, $skipFields)) continue; 

			if(!$this->page->editable($name)) continue; 
			// if($name == 'roles' && $this->processInputRoles($inputfield)) continue; 
			
			if($this->useChildren && $name == 'sortfield') {
				$this->processInputSortfield($inputfield) ;
				continue;
			}

			if($this->useSettings) { 

				if($name == 'template') { 
					$this->processInputTemplate($inputfield); 
					continue; 
				}

				if($name == 'status' && $this->processInputStatus($inputfield)) continue; 
			}


			if($name && $inputfield->isChanged()) {
				$this->page->set($name, $inputfield->value);
			}

			if($inputfield instanceof InputfieldWrapper && count($inputfield->getChildren())) $this->processInput($inputfield, $level + 1); 
		}
	}

	/**
	 * Check to see if the page's template has changed and setup a redirect to a confirmation form if it has
	 *
	 */
	protected function processInputTemplate(Inputfield $inputfield) {
		if(!$inputfield->value) return true; 
		if($this->page->template->noChangeTemplate) return true; 
		if((!$template = $this->templates->get((int) $inputfield->value)) || ($template->id == $this->page->template->id)) return true; 
		if(!$this->isAllowedTemplate($template)) throw new WireException("Template '$template' is not allowed"); 

		// template has changed, set a redirect URL which will confirm the change
		$this->redirectUrl = "template?id={$this->page->id}&template={$template->id}";
		return true; 
	}

	/**
	 * Process the submitted 'status' field and account for the bitwise logic present
	 *
	 */
	protected function processInputStatus(Inputfield $inputfield) {

		$status = $inputfield->value; 
		$value = $this->page->status; 

		if(!is_array($status)) $status = array();

		$statusFlags = array(Page::statusHidden, Page::statusUnpublished); 
		if($this->user->hasPermission('page-lock', $this->page)) $statusFlags[] = Page::statusLocked;

		if($this->config->advanced && $this->user->isSuperuser()) {
			$statusFlags[] = Page::statusSystemID;
			$statusFlags[] = Page::statusSystem; 
		}

		foreach($statusFlags as $flag) {
			if(in_array($flag, $status)) {
				if(!($value & $flag)) $value = $value | $flag; 

			} else if($value & $flag) {
				$value = $value & ~$flag; 
			}
		
		}

		$this->page->status = $value; 
		return true; 
	}

	/**
	 * Process the Children > Sortfield input
	 *
	 */
	protected function processInputSortfield(Inputfield $inputfield) {
		if(!$this->user->hasPermission('page-sort', $this->page)) return true; 
		$sortfield = $this->sanitizer->name($inputfield->value); 
		if($sortfield != 'sort' && !empty($_POST['sortfield_reverse'])) $sortfield = '-' . $sortfield; 
		$this->page->sortfield = $sortfield; 
		return true; 
	}


	/**
	 * Process a delete page request, moving the page to the trash if applicable
	 *
	 */
	protected function deletePage() {

		if(!$this->page->deleteable()) {
			$this->error("This page is not deleteable"); 
			return false; 
		}

		$afterDeleteRedirect = $this->fuel('config')->urls->admin . "page/?open={$this->parent->id}";
		if($this->fuel('page')->process != $this->className()) $afterDeleteRedirect = "../";

		if($this->isTrash || $this->page->template->noTrash) {
			$this->session->message("Deleted page: {$this->page->url}"); 
			$this->pages->delete($this->page, true); 
			$this->session->redirect($afterDeleteRedirect); 

		} else if($this->pages->trash($this->page)) {
			$this->session->message("Moved page to trash: {$this->page->url}"); 
			$this->session->redirect($afterDeleteRedirect); 
			
		} else { 
			$this->error("Unable to move page to trash"); 
			return false;
		}
	}

	/**
	 * Set the headline used in the UI
	 *
	 */
	public function setupHeadline() {
		$page = $this->page ? $this->page : $this->parent; 
		$this->setFuel('processHeadline', $page->get("title|name"));
	}

	/**
	 * Setup the breadcrumbs used in the UI 
	 *
	 */
	public function setupBreadcrumbs() {
		if($this->fuel('page')->process != $this->className()) return;
		$breadcrumbs = new Breadcrumbs();
		$breadcrumbs->add(new Breadcrumb($this->config->urls->admin . 'page/list/', "Pages"));
		$page = $this->page ? $this->page : $this->parent; 

		$pageListConfig = $this->modules->getModuleConfigData('ProcessPageList'); 
		$limit = $pageListConfig['limit'];

		foreach($page->parents() as $p) {
			$parent = $p->parent; 

			// make breadcrumb to go pagelist with page clicked, unless pagination is active in that PageList
			if($limit && $parent->id && $parent->numChildren > $limit && $p->editable()) $url = "./?id={$p->id}"; 
				else $url = "../?open=" . $p->id; 

			$breadcrumbs->add(new Breadcrumb($url, $p->get("title|name"))); 
		}
		$this->setFuel('breadcrumbs', $breadcrumbs); 
	}

	/**
	 * Execute a template change for a page, building an info + confirmation form
	 *
	 */
	public function ___executeTemplate() {

		if(!$this->useSettings || !$this->user->hasPermission('page-template', $this->page))
			throw new WireException("You don't have permission to change the template on this page."); 

		if(!isset($_GET['template'])) throw new WireException("This method requires a 'template' get var"); 
		$template = $this->templates->get((int) $_GET['template']); 
		if(!$template) throw new WireException("Unknown template"); 

		if(!$this->isAllowedTemplate($template)) throw new WireException("That template is not allowed"); 
	
		$form = $this->modules->get("InputfieldForm"); 
		$form->attr('action', 'saveTemplate'); 
		$form->attr('method', 'post'); 
		$form->description = "Change template from '{$this->page->template}' to '$template'";

		$f = $this->modules->get("InputfieldMarkup"); 	
		$f->label = "Confirm template change"; 
		$list = '';
		foreach($this->page->template->fieldgroup as $field) {
			if(!$template->fieldgroup->has($field)) 
				$list .= "<li class='ui-state-highlight'><span class='ui-icon ui-icon-alert'></span> $field</li>";
		}
		if(!$list) $this->executeSaveTemplate($template); 
		$f->description = "Warning, changing the template will delete the following fields:"; 
		$f->attr('value', "<ul>$list</ul>"); 
		$form->append($f); 

		$f = $this->modules->get("InputfieldCheckbox"); 
		$f->attr('name', 'template'); 
		$f->attr('value', $template->id); 
		$f->label = "Are you sure?";		
		$f->description = "Please confirm that you understand the above by clicking the checkbox below.";
		$form->append($f); 

		$f = $this->modules->get("InputfieldHidden"); 
		$f->attr('name', 'id'); 
		$f->attr('value', $this->page->id); 
		$form->append($f); 

		$f = $this->modules->get("InputfieldSubmit"); 
		$form->append($f); 

		$this->fuel('breadcrumbs')->add(new Breadcrumb("./?id={$this->page->id}", $this->page->get("title|name"))); 

		return $form->render();
	}

	/**
	 * Save a template change for a page
	 *
	 */
	public function ___executeSaveTemplate($template = null) {

		if(!$this->useSettings || !$this->user->hasPermission('page-template', $this->page))
			throw new WireException("You don't have permission to change the template on this page."); 

		if(!$this->page->template->noChangeTemplate) { 

			if(!is_null($template) || (isset($_POST['template']) && ($template = $this->templates->get((int) $_POST['template'])))) {
				try { 
					if(!$this->isAllowedTemplate($template)) throw new WireException("Template '$template' is not allowed"); 
					$this->page->template = $template; 
					$this->page->save();
					$this->message("Changed template to '$template'"); 
				} catch(Exception $e) {
					$this->error($e->getMessage()); 
				}
			}
		}

		$this->session->redirect("./?id={$this->page->id}"); 
	}

	/**
	 * Returns an array of templates that are allowed to be used here
	 *
	 */
	protected function getAllowedTemplates() {

		if(is_array($this->allowedTemplates)) return $this->allowedTemplates;

		$templates = array();
		$user = $this->fuel('user');
		$isSuperuser = $user->isSuperuser();
		$page = $this->page;
		$parent = $this->page->parent; 
		$parentEditable = ($parent->id && $parent->editable());

		// current page template is assumed, otherwise we wouldn't be here
		$templates[$page->template->id] = $page->template; 

		// check if they even have permission to change it
		if(!$user->hasPermission('page-template', $page) || $page->template->noChangeTemplate) {
			$this->allowedTemplates = $templates;
			return $templates;
		}

		foreach($this->fuel('templates') as $template) {

			if(isset($templates[$template->id])) continue; 

			if($template->flags & Template::flagSystem) {
				if($template->name == 'user' && $parent->id != $this->config->usersPageID) continue;
				if($template->name == 'role' && $parent->id != $this->config->rolesPageID) continue;
				if($template->name == 'permission' && $parent->id != $this->config->permissionsPageID) continue;
			}

			if(count($template->parentTemplates) && $parent->id && !in_array($parent->template->id, $template->parentTemplates)) {
				// this template specifies it can only be used with certain parents, and our parent's template isn't one of them
				continue;
			}	

			if($parent->id && count($parent->template->childTemplates)) {
				// the page's parent only allows certain templates for it's children
				// if this isn't one of them, then continue; 
				if(!in_array($template->id, $parent->template->childTemplates)) continue; 
			}

			if($isSuperuser) { 
				$templates[$template->id] = $template;

			} else if($template->noParents) {
				// user can't change to a template that has been specified as no more instances allowed
				// except for superuser... we'll let them do it
				continue;

			} else if((!$template->useRoles && $parentEditable) || $user->hasPermission('page-edit', $template)) {
				// determine if the template's assigned roles match up with the users's roles
				// and that at least one of those roles has page-edit permission
				$templates[$template->id] = $template; 
			}
		}

		$this->allowedTemplates = $templates;
		return $templates; 
	}

	/**
	 * Is the given template or template ID allowed here?
	 *
	 */
	protected function isAllowedTemplate($id) {

		// if $id is a template, then convert it to it's numeric ID
		if(is_object($id) && $id instanceof Template) $id = $id->id; 

		$id = (int) $id; 

		// if the template is the same one already in place, of course it's allowed
		if($id == $this->page->template->id) return true; 

		// if we've made it this far, then get a list of templates that are allowed...
		$templates = $this->getAllowedTemplates();

		// ...and determine if the supplied template is in that list
		return isset($templates[$id]); 
	}

	/**
	 * Save only the fields posted
	 *
	 * Field name must be included in server header HTTP_X_FIELDNAME or directly in the POST vars.
	 *
	 * Note that fields that would be not present in POST vars (like a checkbox) are only supported by the HTTP_X_FIELDNAME version.
	 *
	 * Works for custom fields only at present. 
	 *
	 */
	protected function ___ajaxSave() {

		$form = new InputfieldWrapper();
		$keys = array();

		if(isset($_SERVER['HTTP_X_FIELDNAME'])) {
			$keys[] = $this->sanitizer->fieldName($_SERVER['HTTP_X_FIELDNAME']);

		} else {
			foreach($this->input->post as $key => $unused) {
				if($key == 'id') continue; 
				$keys[] = $this->sanitizer->fieldName($key);
			}
		}

		foreach($keys as $key) {

			if(!$field = $this->page->template->fieldgroup->getField($key)) continue; 
			if(!$this->page->editable($key)) continue; 
			if(!$inputfield = $field->getInputfield($this->page)) continue; 

			$inputfield->name = $key;
			$inputfield->value = $this->page->get($key); 
			$form->add($inputfield); 
		}

		$form->processInput($this->input->post); 
		$this->page->setTrackChanges(true); 
		$numFields = 0;
		$lastFieldName = null;

		foreach($form->children() as $inputfield) { 
			$this->page->set($inputfield->name, $inputfield->value); 
			$numFields++; 
			$lastFieldName = $inputfield->name; 
		}

		if($this->page->isChanged()) {
			if($numFields === 1) {
				$this->page->save($lastFieldName); 
				$this->message("Saved page '{$this->page->id}' field '$lastFieldName'"); 
			} else {
				$this->page->save();
				$this->message("Saved page '{$this->page->id}' multiple fields"); 
			}
		} else {
			$this->message("Page not saved (no changes)"); 
		}
	}

	/**
	 * Return instance of the Page being edited
	 *
	 * For Inputfields/Fieldtypes to use if they want to retrieve the editing page rather than the viewing page
	 *
	 */
	public function getPage() {
		return $this->page; 
	}

}

