<?php

/**
 * Class InputfieldImage
 * 
 * Inputfield for FieldtypeImage fields
 * 
 * @property string $extensions Space separated list of allowed image extensions (default="JPG JPEG GIF PNG")
 * @property bool|int $adminThumbs Generate and use thumbnails for output in the admin? (default=false)
 * @property int|string $maxWidth Max width for uploaded images, larger will be sized down (default='')
 * @property int|string $maxHeight Max height for uploaded images, larger will be sized down (default='')
 * @property bool|int $maxReject Reject images that exceed max allowed size? (default=false)
 * @property int|string $minWidth Min width for uploaded images, smaller will be refused (default='')
 * @property int|string $minHeight Min height for uploaded images, smaller will be refused (default='')
 * @property string $itemClass Space separated CSS classes for items rendered by this Inputfield. Generally you should append rather than replace.
 * @property int|bool $defaultGrid Start in grid mode rather than list mode? (default=0)
 * @property int $gridSize Max dimension in pixels for width or height for images in grid mode (default=100)
 * @property int|bool $useImageEditor Whether or not the modal image editor is allowed for this field (default=true)
 * 
 * The following properties default values are pulled from $config->adminThumbOptions and can be overridden 
 * by setting directly to an instance of this Inputfield:
 * 
 * @property int $adminThumbWidth Width for admin thumbnails (default=unspecified)
 * @property int $adminThumbHeight Height for admin thumbnails (default=100)
 * @property int $adminThumbScale Scale for admin thumbnails (default=1.0 or specify 0.5 for hidpi)
 * @property array $imageSizerOptions Options to pass along to the ImageSizer class. See /wire/config.php $imageSizerOptions for details.
 * 
 * 
 */

class InputfieldImage extends InputfieldFile implements InputfieldItemList {

	public static function getModuleInfo() {
		return array(
			'title' => __('Images', __FILE__), // Module Title
			'summary' => __('One or more image uploads (sortable)', __FILE__), // Module Summary
			'version' => 117,
			'permanent' => true, 
			);
	}
	
	protected $variations = array();
	protected $modalClass = 'pw-modal-large';
	
	public function init() {
		parent::init();
		$this->set('extensions', 'JPG JPEG GIF PNG');
		$this->set('adminThumbs', false); // generate and use thumbnails for output?
		$this->set('maxWidth', ''); 
		$this->set('maxHeight', '');
		$this->set('maxReject', 0);
		$this->set('minWidth', '');
		$this->set('minHeight', '');
		
		$this->set('itemClass', 'InputfieldFileItem InputfieldImage ui-widget'); 
		$this->set('defaultGrid', 0);
		$this->set('gridSize', 100); // max dimension (in pixels, width or height) for images in grid mode 
		
		$options = $this->wire('config')->adminThumbOptions;
		if(!is_array($options)) $options = array();
		if(empty($options['width']) && empty($options['height'])) $options['height'] = 100; // default
		$this->set('adminThumbWidth', empty($options['width']) ? 0 : (int) $options['width']);
		$this->set('adminThumbHeight', empty($options['height']) ? 0 : (int) $options['height']);
		$this->set('adminThumbScale', empty($options['scale']) ? 1.0 : (float) $options['scale']);
		
		if(empty($options['imageSizerOptions'])) {
			// properties specified in $options rather than $options['imageSizerOptions'], so we copy them
			$options['imageSizerOptions'] = array();
			foreach($options as $key => $value) {
				if($key == 'height' || $key == 'width' || $key == 'scale') continue;
				$options['imageSizerOptions'][$key] = $value; 
			}
		}
		$this->set('imageSizerOptions', empty($options['imageSizerOptions']) ? array() : $options['imageSizerOptions']);
		$this->set('useImageEditor', 1); 
	}

	public function renderReady(Inputfield $parent = null, $renderValueMode = false) {
		$this->wire('modules')->loadModuleFileAssets('InputfieldFile');
		$this->modules->getInstall("JqueryMagnific");
		if(!$renderValueMode && $this->value instanceof Pageimages) {
			$process = $this->wire('process');
			if($process instanceof WirePageEditor) {
				$page = $process->getPage();
			} else {
				$page = new NullPage();
			}
			$this->variations = $this->value->getAllVariations();
			if($page->id && $this->wire('user')->hasPermission('page-edit-images', $page)) {
				$this->wire('modules')->get('JqueryUI')->use('modal');
			} else {
				$this->useImageEditor = 0;
			}
		}
		return parent::renderReady($parent, $renderValueMode);
	}

	public function ___render() {
		if($this->isAjax) clearstatcache();
		$out = parent::___render();
		if($this->defaultGrid) $out .= "<span class='InputfieldImageDefaultGrid'></span>";
		return $out; 
	}

	/**
	 * Resize images to max width/height if specified in field config and image is larger than max
	 *
	 */
	protected function ___fileAdded(Pagefile $pagefile) {

		$filename = $pagefile->filename; 
		$pagefile2 = null;

		if(!$pagefile->width) { 
			$pagefile->unlink();
			throw new WireException($this->_('Invalid image')); 
		}
		
		if(($this->minWidth && $pagefile->width < $this->minWidth) || ($this->minHeight && $pagefile->height < $this->minHeight)) {
			$actualDimensions = $pagefile->width . 'x' . $pagefile->height; 
			$requiredDimensions = $this->minWidth . 'x' . $this->minHeight;
			throw new WireException(sprintf($this->_('Image of %s does not meet minimum size requirements'), $actualDimensions) . " ($requiredDimensions)"); 
		}

		if(($this->maxWidth && $pagefile->width > $this->maxWidth) || ($this->maxHeight && $pagefile->height > $this->maxHeight)) {
			if($this->maxReject) {
				$actualDimensions = $pagefile->width . '×' . $pagefile->height;
				$requiredDimensions = $this->maxWidth . '×' . $this->maxWidth;
				throw new WireException(sprintf($this->_('Image of %s exceeds maximum allowed size'), $actualDimensions) . " ($requiredDimensions)");
			}
			$pagefile2 = $pagefile->size($this->maxWidth, $this->maxHeight, array('cropping' => false));
			if($pagefile->filename != $pagefile2->filename) {
				unlink($pagefile->filename);
				rename($pagefile2->filename, $pagefile->filename);
			}
			$pagefile->getImageInfo(true); // force it to reload it's dimensions
		}

		if($pagefile2) {
			$this->message($this->_("Image resized to fit maximum allowed dimensions") . " ({$this->maxWidth}x{$this->maxHeight}"); 
		}

		return parent::___fileAdded($pagefile); 
	}

	/**
	 * Get thumbnail image info
	 * 
	 * @param Pageimage $img
	 * @return array of(
	 * 	'thumb' => Pageimage object,
	 * 	'attr' => associative array of image attributes 
	 * 	'markup' => string of markup for <img>, 
	 * 	'error' => error message if applicable
	 * 	);
	 * 
	 */
	public function getAdminThumb(Pageimage $img) {
		
		$thumb = $img; 
		$error = '';
		$gridSize = $this->gridSize;
		$attr = array();
		
		if($this->adminThumbs) {
			
			$thumbHeight = $thumb->height;
			$thumbWidth = $thumb->width;
			$useScale = $this->adminThumbScale > 0 && ((float) $this->adminThumbScale) != 1.0;
			$useResize = ($img->ext == 'svg' && $thumbHeight == '100%') 
				|| ($this->adminThumbHeight && $thumbHeight > ($this->adminThumbHeight * $this->adminThumbScale))
				|| ($this->adminThumbWidth && $thumbWidth > ($this->adminThumbWidth * $this->adminThumbScale));
			
			if($useResize) {
				// create a variation for display with this inputfield
				$thumbHeight = $this->adminThumbHeight;
				$thumbWidth = $this->adminThumbWidth;
				$imageSizerOptions = $this->imageSizerOptions; 
				$thumb = $thumb->size($thumbWidth, $thumbHeight, $imageSizerOptions);
				if($thumb->error) $error = $thumb->error;
			}
			
			if($useScale) {
				if($thumbHeight) $thumbHeight = floor($thumbHeight * $this->adminThumbScale);
				if($thumbWidth) $thumbWidth = floor($thumbWidth * $this->adminThumbScale);
			}
			
			if($thumbHeight && $thumbWidth) {
				$attr['width'] = $thumbWidth;
				$attr['height'] = $thumbHeight; 
				$gridSize = $thumbHeight > $thumbWidth ? $thumbWidth : $thumbHeight;
			} else if($thumbHeight) {
				$attr['height'] = $thumbHeight;
				$gridSize = $thumbHeight;
			} else if($thumbWidth) {
				$attr['width'] = $thumbWidth; 
				$gridSize = $thumbWidth;
			}
		} else if($this->adminThumbScale < 1) {
			// no thumb, but hidpi full size
			$attr['width'] = $thumb->hidpiWidth($this->adminThumbScale);
			// $attr['height'] = $thumb->hidpiHeight($this->adminThumbScale); 
		}

		$url = $thumb->URL;

		// ensure cached image doesn't get shown when replacing same filename
		// if($this->overwrite) $url .= "?m=" . filemtime($img->pathname);

		// if($this->wire('config')->ajax) {
		// 	$mtime = filemtime($thumb->filename());
		//	if($mtime > time() - 15) $url .= "?modified=$mtime"; // for nocache
		// }
		
		$attr['src'] = $url;
		$attr['alt'] = $this->wire('sanitizer')->entities1($img->description);
		$attr['data-gridsize'] = $gridSize;
		$markup = "<img ";
		foreach($attr as $key => $value) $markup .= "$key=\"$value\" ";
		$markup .= " />";
		
		$a = array(
			'thumb' => $thumb, 
			'attr' => $attr, 
			'markup' => $markup, 
			'error' => $error, 
		);
		return $a; 
	}

	/**
	 * Render a Pageimage item
	 * 
	 * @param $pagefile
	 * @param $id
	 * @param $n
	 * @return string
	 * 
	 */
	protected function ___renderItem($pagefile, $id, $n) {

		$thumb = $this->getAdminThumb($pagefile); 
		$error = $thumb['error'] ? "<span class='ui-state-error-text'>" . $this->wire('sanitizer')->entities($thumb['error']) . "</span>" : "";
		
		$editable = (int) $this->useImageEditor;
		if($this->renderValueMode) $editable = false;
		if(strpos($this->name, '_repeater') && preg_match('/_repeater\d+$/', $this->name)) $editable = false;
		if($pagefile->ext == 'svg') $editable = false;

		$variations = isset($this->variations[$pagefile->name]) ? $this->variations[$pagefile->name] : array();
		
		if(count($variations) && $editable) {
			$cnt = count($variations); 
			$variationURL = $this->wire('config')->urls->admin . 
				"page/image/variations/?id={$pagefile->page->id}&file=$pagefile->name&modal=1&varcnt=varcnt_$id";
			$variationInfo = "\n\t\t\t&nbsp;" . 
				"<a class='InputfieldImageVariationCnt pw-modal $this->modalClass' data-buttons='button' " . 
				"href='$variationURL' title='" . sprintf($this->_('Variations of %s'), $pagefile->name) . "'>" . 
				"<i class='fa fa-files-o'></i>&nbsp;<span id='varcnt_$id'>$cnt</span></a>"; 
		} else {
			$variationInfo = '';
		}
		
		$pageID = $pagefile->pagefiles->page->id; 
		if($editable) {
			$editURL = $this->wire('config')->urls->admin . "page/image/edit/?id=$pageID&file=$pageID,$pagefile->name&rte=0&field=$this->name";
		} else {
			$editURL = '';
		}
		$editTitle = "$pagefile->name ({$pagefile->width}x{$pagefile->height})";
		$fileStats = str_replace(' ', '&nbsp;', $pagefile->filesizeStr) . ", {$pagefile->width}x{$pagefile->height} ";

		$out = "\n\t\t<p class='InputfieldFileInfo InputfieldItemHeader ui-widget ui-widget-header ui-helper-clearfix'>";
		
		if(!$this->renderValueMode) $out .= 
			"\n\t\t\t<span class='HideIfSingle HideIfEmpty InputfieldFileDrag'><i class='fa fa-sort'></i>&nbsp;</span>" .
			"\n\t\t\t<i class='fa fa-caret-right InputfieldFileDrag HideIfMultiple'></i> ";
		
		if($this->uploadOnlyMode) {
			
			$out .= 
				"\n\t\t\t<span class='InputfieldFileName'>$pagefile->basename</span> " . 
				"\n\t\t\t<span class='InputfieldFileStats'>$fileStats</span> ";
			
		} else {
	
			if(!$this->renderValueMode) $out .=
				"\n\t\t\t<label class='InputfieldFileDelete'>" .
				"<input type='checkbox' name='delete_$id' value='1' title='" . $this->_('Delete') . "' />" .
				"<i class='fa fa-fw fa-trash'></i></label>" .
				"\n\t\t\t<a class='InputfieldFileMove InputfieldFileMoveBottom' href='#' title='" . $this->_('Move to bottom') . "'>" .
				"<i class='fa fa-fw fa-angle-double-down'></i></a> " .
				"\n\t\t\t<a class='InputfieldFileMove InputfieldFileMoveTop' href='#' title='" . $this->_('Move to top') . "'>" .
				"<i class='fa fa-fw fa-angle-double-up'></i></a> ";
			
			$displayName = $this->getDisplayBasename($pagefile);
			
			if($editURL) {
				$out .=
					"\n\t\t\t<a class='InputfieldFileName pw-modal $this->modalClass' title='$pagefile->basename: $editTitle' href='$editURL' " .
					"data-buttons='#non_rte_dialog_buttons button' " .
					"data-autoclose='1' data-close='#non_rte_cancel'>$displayName " . 
					"<i class='fa fa-pencil ui-priority-secondary'></i></a> ";
			} else {
				$out .= 
					"\n\t\t\t<a class='InputfieldFileName InputfieldFileLink' " . 
					"target='_blank' title='$pagefile->basename' href='$pagefile->URL'>$displayName</a> ";
			}
			$out .= 
				"\n\t\t\t<span class='InputfieldFileStats'>$fileStats $variationInfo</span> ";
			
		}
		
		$out .= "\n\t\t</p>" . // .InputfieldFileInfo.InputfieldItemHeader
				"\n\t\t<div class='InputfieldFileData ui-widget ui-widget-content'>" .
				"\n\t\t\t<div class='InputfieldImagePreview'>";
		
		if(!file_exists($pagefile->filename()) || !$pagefile->filesize()) {
			$out .= "<span class='ui-state-error-text'><i class='fa fa-exclamation-triangle'></i> " . 
				$this->_('File cannot be displayed') . "</span>";
		} else {
			$out .= "\n\t\t\t\t<a class='InputfieldFileLink' target='_blank' href='{$pagefile->URL}'>$thumb[markup]</a>";
		}
			
		if(!$this->uploadOnlyMode && $editable) {
			$out .= 
				"\n\t\t\t\t<div class='InputfieldImageActions'>" .
				"\n\t\t\t\t\t<a title='$editTitle' href='$editURL' class='pw-modal $this->modalClass' " .
				"data-buttons='#non_rte_dialog_buttons button' data-autoclose='1' data-close='#non_rte_cancel'>" .
				"<i class='fa fa-fw fa-crop'></i></a>" .
				"\n\t\t\t\t</div>";
		}
		
		$out .= 
			"\n\t\t\t</div>" . // .InputfieldImagePreview
			"\n\t\t\t" . $error . $this->renderItemDescriptionField($pagefile, $id, $n) . 
			"\n\t\t\t<input class='InputfieldFileSort' type='text' name='sort_$id' value='$n' />" . 
			"\n\t\t</div>"; // .InputfieldFileData

		return $out; 
	}

	/**
	 * Template method: allow items to be collapsed? Override default from InputfieldFile
	 *
	 * @return bool
	 *
	 */
	protected function allowCollapsedItems() {
		return false;
	}

	/**
	 * Configure field
	 * 
	 * @return InputfieldWrapper
	 * 
	 */
	public function ___getConfigInputfields() {

		$inputfields = parent::___getConfigInputfields();
	
		$field = $this->modules->get('InputfieldCheckbox'); 
		$field->attr('name', 'adminThumbs'); 
		$field->attr('value', 1); 
		$field->attr('checked', $this->adminThumbs ? 'checked' : ''); 
		$field->label = $this->_('Display thumbnails in page editor?'); 
		$field->description = $this->_('Thumbnails take up less space and make it easier to sort multiple images. If unchecked, the full (original) size image will be shown in the page editor.'); // Display thumbnails description
		$inputfields->add($field);
		
		$field = $this->modules->get("InputfieldRadios"); 
		$field->attr('name', 'defaultGrid'); 
		$field->label = $this->_('Default View'); 
		$field->addOption(0, $this->_('Rows')); 
		$field->addOption(1, $this->_('Grid')); 
		// $field->showIf = 'maxFiles!=1';
		$field->optionColumns = 1; 
		$field->description = $this->_('Either view can be toggled by clicking the grid/row icon in the image field. This just defines which one is the default. The rows view is the recommended default.'); 
		$field->attr('value', (int) $this->defaultGrid); 
		$inputfields->add($field); 

		$fieldset = $this->modules->get('InputfieldFieldset');
		$fieldset->label = $this->_("Max Image Dimensions");
		$fieldset->collapsed = $this->maxWidth || $this->maxHeight ? Inputfield::collapsedNo : Inputfield::collapsedYes; 
		$fieldset->description = $this->_("Optionally enter the max width and/or height of uploaded images. If specified, images will be resized at upload time when they exceed either the max width or height. The resize is performed at upload time, and thus does not affect any images in the system, or images added via the API."); // Max image dimensions description

		$description = $this->_("Enter the value in number of pixels or leave blank for no limit."); // Min/Max width/height description
		$field = $this->modules->get("InputfieldInteger"); 
		$field->attr('name', 'maxWidth'); 
		$field->attr('value', $this->maxWidth ? (int) $this->maxWidth : ''); 
		$field->label = $this->_("Max width for uploaded images"); 
		$field->description = $description;
		$field->columnWidth = 50; 
		$fieldset->add($field); 

		$field = $this->modules->get("InputfieldInteger"); 
		$field->attr('name', 'maxHeight'); 
		$field->attr('value', $this->maxHeight ? (int) $this->maxHeight : ''); 
		$field->label = $this->_("Max height for uploaded images"); 
		$field->description = $description;
		$field->columnWidth = 50; 
		$fieldset->add($field);

		// maxReject option comes from @JanRomero PR #1051
		$field = $this->modules->get("InputfieldCheckbox");
		$field->attr('name', 'maxReject');
		$field->attr('value', (int) $this->maxReject);
		$field->attr('checked', ((int) $this->maxReject) ? 'checked' : '');
		$field->label = $this->_('Refuse images exceeding max dimensions?');
		$field->showIf = 'maxWidth|maxHeight>0';
		$field->description = $this->_('If checked, images that exceed max width/height will be refused rather than resized.');
		$fieldset->add($field);

		$inputfields->add($fieldset);
	
		// min image dimensions
		$fieldset = $this->modules->get('InputfieldFieldset');
		$fieldset->label = $this->_("Min Image Dimensions");
		$fieldset->collapsed = $this->minWidth || $this->minHeight ? Inputfield::collapsedNo : Inputfield::collapsedYes;
		$fieldset->description = $this->_("Optionally enter the minimum width and/or height of uploaded images. If specified, images that don't meet these minimums will be refused."); // Max image dimensions description

		$field = $this->modules->get("InputfieldInteger");
		$field->attr('name', 'minWidth');
		$field->attr('value', $this->minWidth ? (int) $this->minWidth : '');
		$field->label = $this->_("Min width for uploaded images");
		$field->description = $description;
		$field->columnWidth = 50;
		$fieldset->add($field);

		$field = $this->modules->get("InputfieldInteger");
		$field->attr('name', 'minHeight');
		$field->attr('value', $this->minHeight ? (int) $this->minHeight : '');
		$field->label = $this->_("Min height for uploaded images");
		$field->description = $description;
		$field->columnWidth = 50;
		$fieldset->add($field);

		$inputfields->add($fieldset); 
		
		return $inputfields; 	
	}

	/**
	 * Specify which config inputfields can be used with template/field contexts
	 * 
	 * @param Field $field
	 * @return array
	 * 
	 */
	public function ___getConfigAllowContext($field) {
		$a = array('adminThumbs', 'defaultGrid'); 
		return array_merge(parent::___getConfigAllowContext($field), $a); 
	}
}
