<?php

class InputfieldCheckboxes extends InputfieldSelectMultiple implements InputfieldHasArrayValue {

	public static function getModuleInfo() {
		return array(
			'title' => __('Checkboxes', __FILE__), // Module Title
			'summary' => __('Multiple checkbox toggles', __FILE__), // Module Summary
			'version' => 100,
			'permanent' => true, 
			);
	}

	public function init() {
		$this->set('table', false); 
		$this->set('thead', ''); 
		$this->set('optionColumns', 0); 
		parent::init();
		$this->set('size', null); // cancel 'size' attribute used by select multiple
	}

	public function ___render() {	
		$out = '';
		$table = null;
		$columns = (int) $this->optionColumns;
		$inline = $columns === 1 || $columns > 10; 
		$liAttr = '';
		$ulClass = '';

		if($this->table) {
			$table = $this->modules->get("MarkupAdminDataTable"); 
			$table->setEncodeEntities(false);
			if($this->thead) $table->headerRow(explode('|', htmlspecialchars($this->thead))); 

		} else if($columns) {

			if($inline) {
				$ulClass = 'InputfieldCheckboxesFloated';
			} else {
				$liWidth = round(100 / $columns)-1;  // 1% padding-right added from stylesheet
				$liAttr = " style='width: {$liWidth}%;'";
				$ulClass = 'InputfieldCheckboxesColumns';
			}

			$ulClass .= " ui-helper-clearfix";

		} else {
			$ulClass = 'InputfieldCheckboxesStacked';
		}

		if(!$table) $out = "\n<ul class='$ulClass'>";

		foreach($this->getOptions() as $key => $value) {
			$checked = '';

			if($this->isOptionSelected($key)) $checked = " checked='checked'";
			$id = $this->id . "_" . $this->fuel('sanitizer')->name($key); 

			$attrs = $this->getOptionAttributes($key);
			unset($attrs['checked'], $attrs['selected']); 
			$attrs = $this->getOptionAttributesString($attrs);
			if($attrs) $attrs = ' ' . $attrs; 

			$value = $this->entityEncode($value); 

			$input = "<label$attrs>" . 
				"<input$checked " . 
				"type='checkbox' " . 
				"name='{$this->name}[]' " . 
				"id='$id' " . 
				"value='" . htmlspecialchars($key, ENT_QUOTES) . "' /> "; 

			if($table) {
				$value = explode("|", nl2br($value));
				$value[0] = $input . $value[0] . "</label>";
				$table->row($value); 
			} else {
				$out .= "\n\t<li$liAttr>" . $input . $value . "</label></li>";
			}
			
		}

		if($table) $out .= $table->render();
			else $out .= "\n</ul>";

		return $out; 

	}

	public function set($key, $value) {
		if($key == 'optionColumns') {
			$value = (int) $value;
			if($value < 0) $value = 0;
			if($value > 10) $value = 10;
		}
		return parent::set($key, $value); 
	}

	public function ___getConfigInputfields() {
		$inputfields = parent::___getConfigInputfields(); 
		$f = wire('modules')->get('InputfieldInteger');
		$f->label = $this->_('Columns of Checkboxes');
		$f->description = $this->_('If you want the checkboxes to display in columns (rather than stacked), enter the number of columns you want to use (up to 10). To display checkboxes side-by-side (inline) enter 1.'); 
		$f->attr('name', 'optionColumns'); 
		$f->attr('value', (int) $this->optionColumns); 
		$inputfields->add($f);	
		return $inputfields; 
	}

}
