<?php

class InputfieldMarkup extends InputfieldWrapper {

	public static function getModuleInfo() {
		return array(
			'title' => __('Markup', __FILE__),
			'summary' => __('Contains any other markup and optionally child Inputfields', __FILE__),
			'version' => 100,
			'permanent' => true, 
			);
	}

	public function ___render() {
		$out = '';
		if($this->description) {
			$out .= "\n<p class='description'>{$this->description}</p>";
			$this->description = ''; // prevents it from appearing again at the bottom
		}
		if($this->attr('value')) $out .= "\n" . $this->attr('value'); 
		$out .= parent::___render(); 
		return $out; 
	}
	
}

