<?php

class InputfieldRadios extends InputfieldSelect {

	public static function getModuleInfo() {
		return array(
			'title' => 'Radio Buttons',
			'version' => 100,
			'summary' => 'Radio buttons for selection of a single item',
			'permanent' => true, 
			);
	}

	public function ___render() {	

		$out =	"\n\t<ul>"; 

		foreach($this->getOptions() as $key => $value) {
			$checked = '';

			if($this->isOptionSelected($key)) $checked = " checked='checked'";
			$id = $this->id . "_" . $this->fuel('sanitizer')->name($key); 

			$attrs = $this->getOptionAttributesString($key);
			if($attrs) $attrs = ' ' . $attrs; 

			$out .= "\n\t\t<li><label$attrs>" . 
				"<input$checked " . 
				"type='radio' " . 
				"name='{$this->name}' " . 
				"id='$id' " . 
				"value='" . htmlspecialchars($key, ENT_QUOTES) . "' />" . $this->entityEncode($value) . 
				"</label></li>";
		}

		$out .=	"\n\t</ul>";

		return $out; 
	}

}
