<?php

/**
 * An Inputfield for handling a password
 *
 */
class InputfieldPassword extends InputfieldText {

	public static function getModuleInfo() {
		return array(
			'title' => 'Password',
			'version' => 100,
			'summary' => "Password input that doesn't ever echo the input back.",
			'permanent' => true, 
			);
	}

	public function __construct() {
		parent::__construct();
		$this->attr('type', 'password'); 
		$this->attr('size', 50); 
		$this->attr('maxlength', 128); 
	}

	public function ___render() {
		$value = $this->attr('value'); 
		$trackChanges = $this->trackChanges();
		if($trackChanges) $this->setTrackChanges(false);
		$this->attr('value', '');	
		$out = parent::___render();
		$this->attr('value', $value);
		if($trackChanges) $this->setTrackChanges(true);
		return $out; 
	}
}
