<?php

class InputfieldRadios extends InputfieldSelect {

	public static function getModuleInfo() {
		return array(
			'title' => __('Radio Buttons', __FILE__), // Module Title
			'summary' => __('Radio buttons for selection of a single item', __FILE__), // Module Summary
			'version' => 100,
			'permanent' => true, 
			);
	}

	public function ___render() {	

		$out =	"\n\t<ul>"; 

		foreach($this->getOptions() as $key => $value) {
			$checked = '';

			$id = $this->id . "_" . $this->fuel('sanitizer')->name($key); 

			$attrs = $this->getOptionAttributes($key);
			//if(!empty($attrs['selected'])) $attrs['checked'] = 'checked';

			/*
			if($this->isOptionSelected($key) || 
				(
					!strlen($this->attr('value')) && 
					!empty($attrs['checked'])
				)
			) $checked = " checked='checked'";
			*/
			if($this->isOptionSelected($key)) $checked = " checked='checked'";

			unset($attrs['selected'], $attrs['checked']); 
			$attrs = $this->getOptionAttributesString($attrs);
			if($attrs) $attrs = ' ' . $attrs; 

			$out .= "\n\t\t<li><label$attrs>" . 
				"<input$checked " . 
				"type='radio' " . 
				"name='{$this->name}' " . 
				"id='$id' " . 
				"value='" . htmlspecialchars($key, ENT_QUOTES) . "' />" . $this->entityEncode($value) . 
				"</label></li>";
		}

		$out .=	"\n\t</ul>";

		return $out; 
	}

}
