<?php

/**
 * An Inputfield for handling XHTML "hidden" form inputs
 *
 */
class InputfieldHidden extends Inputfield {

	public static function getModuleInfo() {
		return array(
			'title' => __('Hidden', __FILE__), // Module Title
			'version' => 100,
			'summary' => __('Hidden value in a form', __FILE__), // Module Summary
			'permanent' => true, 
			);
	}

	public function __construct() {
		parent::__construct();
		$this->setAttribute('type', 'hidden'); 
	}

	public function ___render() {
		return "\n<input " . $this->getAttributesString() . " />"; 
	}
	
}
