<?php

class InputfieldFloat extends InputfieldInteger {
	
	public static function getModuleInfo() {
		return array(
			'title' => __('Float', __FILE__), // Module Title
			'summary' => __('Floating point number with precision', __FILE__), // Module Summary
			'version' => 100,
			'permanent' => true, 
			);
	}

	public function __construct() {
		$this->set('precision', 2); 
		parent::__construct();
	}

	protected function sanitizeValue($value) {
		return strlen("$value") ? round((float) $value, $this->precision) : '';
	}

}
