<?php

class InputfieldFieldset extends InputfieldWrapper {

	public static function getModuleInfo() {
		return array(
			'title' => __('Fieldset', __FILE__), // Module Title
			'summary' => __('Groups one or more fields together in a container', __FILE__), // Module Summary
			'version' => 100,
			'permanent' => true, 
			);
	}

	public function ___render() {
		return parent::___render();
	}
	
}

