<?php

/**
 * 
 *
 */
class InputfieldMarkup extends InputfieldWrapper {

	public static function getModuleInfo() {
		return array(
			'title' => 'Markup',
			'version' => 100,
			'summary' => 'Contains any other markup and optionally child Inputfields',
			'permanent' => true, 
			);
	}

	public function ___render() {
		$out = '';
		// if($this->label) $out .= "\n<label>{$this->label}</label>";
		if($this->description) {
			$out .= "\n<p class='description'>{$this->description}</p>";
			$this->description = ''; // prevents it from appearing again at the bottom
		}
		if($this->attr('value')) $out .= "\n" . $this->attr('value'); 
		$out .= parent::___render(); 
		return $out; 
	}
	
}

