<?php

class InputfieldCheckboxes extends InputfieldSelectMultiple implements InputfieldHasArrayValue {

	public static function getModuleInfo() {
		return array(
			'title' => 'Checkboxes',
			'version' => 100,
			'summary' => 'Multiple checkbox toggles',
			'permanent' => true, 
			);
	}

	public function ___render() {	

		// $out = "\n<fieldset id='{$this->id}' class='{$this->className}'>" . 
		// 	"\n\t<legend>" . htmlspecialchars($this->label) . "</legend>" . 

		$out = "\n\t<ul>"; 

		foreach($this->getOptions() as $key => $value) {
			$checked = '';

			if($this->isOptionSelected($key)) $checked = " checked='checked'";
			$id = $this->id . "_" . $this->fuel('sanitizer')->name($key); 

			$attrs = $this->getOptionAttributesString($key);
			if($attrs) $attrs = ' ' . $attrs; 

			$out .= "\n\t\t<li><label$attrs>" . 
				"<input$checked " . 
				"type='checkbox' " . 
				"name='{$this->name}[]' " . 
				"id='$id' " . 
				"value='" . htmlspecialchars($key, ENT_QUOTES) . "' />" . htmlspecialchars($value) . 
				"</label></li>";
			
		}

		$out .=	"\n\t</ul>"; 
		//	"\n</fieldset>";

		return $out; 

	}
}
