<?php

class InputfieldSelectMultiple extends InputfieldSelect implements InputfieldHasArrayValue {

	public static function getModuleInfo() {
		return array(
			'title' => __('Select Multiple', __FILE__), // Module Title
			'summary' => __('Select multiple items from a list', __FILE__), // Module Summary
			'version' => 100,
			'permanent' => true, 
			);
	}

	public function __construct() {
		parent::__construct();
		$this->setAttribute('multiple', 'multiple'); 
	}

	/**
	 * Add options only if they are non-blank
	 *
	 * We don't need blank options in a select multiple since the unselected state involves no selected options
	 *
	 */
	public function addOption($value, $label = null, array $attributes = null) {
		if(!$value) return $this; 
		return parent::addOption($value, $label, $attributes); 
	}


}
