<?php

/**
 * ProcessWire Permission Process
 *
 * For more details about how Process modules work, please see: 
 * /wire/core/Process.php 
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2012 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessPermission extends ProcessPageType {

	static public function getModuleInfo() {
		return array(
			'title' => __('Permissions', __FILE__), // getModuleInfo title
			'version' => 100, 
			'summary' => __('Manage system permissions', __FILE__), // getModuleInfo summary
			'permanent' => true, 
			
			// add this permission if you want this Process available for roles other than Superuser
			'permission' => 'permission-admin',
			); 
	}
	
}

