<?php

/**
 * ProcessWire Logout Process
 *
 * Logs out the current user and gives them a link to login again or go to the site. 
 * 
 * For more details about how Process modules work, please see: 
 * /wire/core/Process.php 
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessLogout extends Process {

	public static function getModuleInfo() {
		return array(
			'title' => 'Logout',          
			'summary' => 'Logout of ProcessWire', 
			'version' => 100, 
			'permanent' => false, 
			);
	}

	/**	
	 * Logout the user and call the render() method to display a menu
	 *
	 */
	public function ___execute() {
		$this->fuel('session')->logout();
		$this->message("You have logged out"); 
		return $this->render();
	}	

	/**
	 * Render a short menu of post-logout options
	 *
	 */
	protected function render() {
		$config = $this->fuel("config"); 
		return 	"\n<ul class='actions'>" . 
			"\n<li><a href='{$config->urls->root}'>Site</a></li>" . 
			"\n<li><a href='../login/'>Login</a></li>" . 
			"\n</ul>";
	}
}

