<?php

/**
 * A Page List Selector for selecting a single page
 *
 */
class InputfieldPageListSelect extends Inputfield {

	public static function getModuleInfo() {
		return array(
			'title' => 'Page List Select',
			'version' => 100,
			'summary' => 'Selection of a single page from a ProcessWire page tree list',
			'permanent' => true, 
			);
	}

	public function init() {
		$this->fuel('modules')->get('ProcessPageList'); // prerequisite module
		$this->set('parent_id', 0); 
		$this->set('labelFieldName', 'title'); 
		$this->set('startLabel', $this->_('Change')); 
		$this->set('cancelLabel', $this->_('Cancel'));
		$this->set('selectLabel', $this->_('Select'));
		$this->set('unselectLabel', $this->_('Unselect')); 
		parent::init();
	}

	public function ___render() {

		if(!strlen($this->parent_id)) {
			$this->error("Field '{$this->label}' (#{$this->id}) requires a parent page to be set. Please select a parent, or choose another Inputfield type."); 
			return "<p class='error'>Unable to render this field due to missing parent page in field settings.</p>";
		}

		$out =	"\n<input type='text' " . $this->getAttributesString() . " />" . 
			"\n<script>$(document).ready(function() { " . 
			"var t = $('#{$this->id}'); " . 
			"t.ProcessPageList({ " . 
				"mode: 'select', " . 
				"rootPageID: {$this->parent_id}, " . 
				"selectAllowUnselect: " . ($this->required ? "false" : "true") . ", " . 
				"selectStartLabel: \"{$this->startLabel}\", " . 
				"selectShowPageHeader: true, " . 
				"selectSelectLabel: \"{$this->selectLabel}\", " . 
				"selectUnselectLabel: \"{$this->unselectLabel}\", " . 
				"selectCancelLabel: \"{$this->cancelLabel}\" " . 
			"}).hide()" . 
			"});</script>";

		return $out; 
	}

	public function ___processInput(WireInputData $input) {
		parent::___processInput($input); 
		$this->value = (int) $this->value; 
		return $this; 
	}
	
}
