<?php

/**
 * ProcessWire Page Table Fieldtype
 *
 * Concept by Antti Peisa
 * Code by Ryan Cramer
 * Sponsored by Avoine
 *
 * ProcessWire 2.x 
 * Copyright (C) 2014 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://processwire.com
 *
 */

class FieldtypePageTable extends FieldtypeMulti implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'ProFields: Page Table',
			'version' => 4,
			'summary' => 'A fieldtype containing a group of editable pages.',
			'installs' => 'InputfieldPageTable',
			'autoload' => true, 
			'requires' => 'ProcessWire>=2.4.2'
			);
	}

	public function init() {

		$pages = $this->wire('pages'); 
		$pages->addHookAfter('delete', $this, 'hookPagesDelete');
		$pages->addHookAfter('deleteReady', $this, 'hookPagesDeleteReady'); 
		$pages->addHookAfter('cloned', $this, 'hookPagesCloned'); 
	}

	public function hookPagesDelete(HookEvent $event) {
		$page = $event->arguments(0); 
		foreach($this->wire('fields') as $field) {
			if(!$field->type instanceof FieldtypePageTable) continue; 
			$table = $this->wire('database')->escapeTable($field->table); 
			$sql = "DELETE FROM `$table` WHERE pages_id=:pages_id OR data=:data";
			$query = wire('database')->prepare($sql); 
			$query->bindValue(':pages_id', (int) $page->id); 
			$query->bindValue(':data', (int) $page->id); 
			$query->execute();
		}
	}

	public function hookPagesDeleteReady(HookEvent $event) {
		$page = $event->arguments(0); 
		foreach($page->template->fieldgroup as $field) {
			if(!$field->type instanceof FieldtypePageTable) continue; 
			if(!$field->parent_id || !$field->autoTrash) continue; 
			$value = $page->getUnformatted($field->name); 
			if(!count($value)) continue; 
			foreach($value as $item) {	
				if($item->isTrash()) continue; 
				$this->wire('pages')->message("Auto Trash Item: $item->url", Notice::debug); 
				$this->wire('pages')->trash($item); 
			}
		}
	}

	public function hookPagesCloned(HookEvent $event) {

		static $clonedIDs = array();

		$page = $event->arguments(0); 
		$copy = $event->arguments(1); 

		if(in_array($copy->id, $clonedIDs)) return;
		$clonedIDs[] = $copy->id; 
	
		foreach($copy->template->fieldgroup as $field) {
			if(!$field->type instanceof FieldtypePageTable) continue; 
			if(!$field->parent_id) continue; // let that be handled manually since recursive clones are already an option
			$value = $copy->getUnformatted($field->name); 
			if(!count($value)) continue; 
			$newValue = new PageArray();
			foreach($value as $item) {
				try { 
					$newItem = $this->wire('pages')->clone($item); 
					if($newItem->id) {
						$newValue->add($newItem); 
						$this->wire('pages')->message("Cloned item $item->path", Notice::debug); 
					}
				} catch(Exception $e) {
					$this->wire('pages')->error("Error cloning $item->path"); 
				}
			}
			$copy->set($field->name, $newValue); 
			$copy->save($field->name); 
		}
	}

	public function ready() {
		if(	$this->wire('config')->ajax && 
			$this->wire('input')->get('InputfieldPageTableField') && 
			$this->wire('user')->isLoggedin() && 
			$this->wire('page')->template == 'admin') {
			// handle ajax request to render table
			require_once($this->wire('config')->paths->InputfieldPageTable . 'InputfieldPageTableAjax.php'); 
			new InputfieldPageTableAjax();
		}
	}

	/**
	* Return the database schema in predefined format 
	*
	*/
	public function getDatabaseSchema(Field $field) {
		$schema = parent::getDatabaseSchema($field);
		$schema['data'] = 'int NOT NULL';
		$schema['keys']['data'] = 'KEY data (data, pages_id, sort)';
		return $schema;
	}

	public function getMatchQuery($query, $table, $subfield, $operator, $value) {
		return $this->wire('modules')->get('FieldtypePage')->getMatchQuery($query, $table, $subfield, $operator, $value); 	
	}

	public function getInputfield(Page $page, Field $field) {
		$inputfield = $this->modules->get('InputfieldPageTable'); 
		$inputfield->attr('value', $page->getUnformatted($field->name)); 
		return $inputfield; 
	}

	public function sanitizeValue(Page $page, Field $field, $value) {
		if(is_array($value) && count($value)) $value = $this->wakeupValue($page, $field, $value); 
		if(!$value instanceof PageArray) return new PageArray();	
		foreach($value as $item) {
			if($this->isValidItem($page, $field, $item)) continue; 
			$value->remove($item); 
		}
		return $value; 
	}

	protected function isValidItem(Page $page, Field $field, Page $item) {
		//if($item->parent_id != $page->id) return false; 
		if($item->template->id != $field->template_id) return false; 
		return true; 
	}


	public function getBlankValue(Page $page, Field $field) {
		return new PageArray();
	}

	public function ___formatValue(Page $page, Field $field, $value) {
		$formatted = new PageArray();
		if(!$value instanceof PageArray) return $formatted; 
		foreach($value as $item) {
			if($item->status >= Page::statusHidden) continue; 
			$formatted->add($item); 
		}
		return $formatted; 
	}

	public function ___sleepValue(Page $page, Field $field, $value) {
		$sleepValue = array();
		if(!$value instanceof PageArray) return $sleepValue; 
		foreach($value as $item) {
			if(!$item->id) continue; 
			if(!$this->isValidItem($page, $field, $item)) continue; 
			$sleepValue[] = $item->id; 
		}
		return $sleepValue; 
	}

	public function ___wakeupValue(Page $page, Field $field, $value) {
		if(!is_array($value) || !count($value) || !$field->template_id) return $this->getBlankValue($page, $field); 
		$template = $this->wire('templates')->get($field->template_id); 
		$items = $this->wire('pages')->getById($value, $template); 
		return $items; 
	}

	public function ___getSelectorInfo(Field $field, array $data = array()) {
		$info = $this->wire('modules')->get('FieldtypePage')->getSelectorInfo($field, $data); 
		$info['input'] = 'none';
		return $info; 
	}

	/**
	 * Return configuration fields definable for each FieldtypePage
	 *
	 */
	public function ___getConfigInputfields(Field $field) {

		$inputfields = parent::___getConfigInputfields($field);

		$f = $this->wire('modules')->get('InputfieldSelect');
		$f->attr('name', 'template_id');
		$f->label = $this->_('Select a template for items');
		$f->addOption(0, ''); 
		foreach($this->wire('templates') as $template) $f->addOption($template->id, $template->name); 
		$f->attr('value', (int) $field->template_id);
		$f->required = true; 
		$f->description = $this->_('This is the template that will be used by pages managed from this field. You may wish to create a new template specific to the needs of this field.'); 
		$f->notes = $this->_('Please hit Save after selecting a template and the remaining configuration on the Input tab will contain more context.'); 
		$inputfields->add($f);

		$f = $this->wire('modules')->get('InputfieldPageListSelect'); 
		$f->attr('name', 'parent_id'); 
		$f->label = $this->_('Select a parent for items'); 
		$f->description = $this->_('All items created and managed from this field will live under the parent you select here.'); 
		$f->notes = $this->_('This is optional. If no parent is selected, then items will be placed as children of the page being edited.'); 
		$f->collapsed = $field->parent_id ? Inputfield::collapsedNo : Inputfield::collapsedYes;
		$f->attr('value', (int) $field->parent_id); 
		$inputfields->add($f);

		$f = $this->wire('modules')->get('InputfieldCheckbox'); 
		$f->attr('name', 'autoTrash'); 
		$f->attr('value', 1); 
		if($field->autoTrash) $f->attr('checked', 'checked'); 
		$f->label = $this->_('Trash items when page is deleted?'); 
		$f->description = $this->_('When checked, items created/managed by a given page will be automatically trashed when that page is deleted. If not checked, the items will remain under the parent you selected above.'); 
		$f->notes = $this->_('This option applies only if you have selected a parent above.'); 
		$f->collapsed = Inputfield::collapsedBlank;
		$inputfields->add($f); 

		return $inputfields;
	}


}

