<?php

/**
 * ProcessWire Fieldset Tabs
 *
 * These are the same as FieldsetOpen except that they are displayed in tabs rather than normal fieldsets. 
 *
 * For documentation about the fields used in this class, please see:  
 * /wire/core/Fieldtype.php
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

require_once("FieldtypeFieldsetOpen.module"); 

class InputfieldFieldsetTabOpen extends InputfieldFieldsetOpen { 

	public function ___getConfigInputfields() {
		$inputfields = parent::___getConfigInputfields();
		$inputfields->remove($inputfields->get('collapsed')); 
		$inputfields->remove($inputfields->get('columnWidth')); 
		return $inputfields; 
	}

} 

class FieldtypeFieldsetTabOpen extends FieldtypeFieldsetOpen {

	public static function getModuleInfo() {
		return array(
			'title' => 'Fieldset in Tab (Open)',
			'version' => 100,
			'summary' => 'Open a fieldset to group fields. Same as Fieldset (Open) except that it displays in a tab instead.',
			'permanent' => true, 
			);
	}

	public function getInputfield(Page $page, Field $field) {
		$inputfield = new InputfieldFieldsetTabOpen();
		$inputfield->class = $this->className();
		return $inputfield; 
	}

	public function ___getConfigInputfields(Field $field) {
		$inputfields = parent::___getConfigInputfields($field);
		$inputfields->remove($inputfields->get('collapsed')); 
		return $inputfields; 
	}

}


