<?php

/**
 * ProcessWire PageRenderFields Module
 *
 * Adds $page->renderFields() and $page->images->render() methods 
 * that return basic markup for output during development and debugging.
 * It hooks into all instances of the the Page and Pageimages classes.
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class MarkupPageFields extends WireData implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'Markup Page Fields', 
			'version' => 100, 
			'summary' => 
				'Adds $page->renderFields() and $page->images->render() methods ' . 
				'that return basic markup for output during development and debugging.',
			'permanent' => true, 
			'singular' => true, 
			'autoload' => true, 
			);
	}

	/**
	 * Initialize the hooks
	 *
	 */
	public function init() {
		$this->addHook('Page::renderFields', $this, 'renderPageFields'); 
		$this->addHook('Pageimages::render', $this, 'renderPageImages'); 
	}

	/**
	 * Return a string with the rendered output of a FieldtypeImages field
	 *
	 * Example, assuming you have a FieldtypeImage field called 'images' on your page: 
	 * echo $page->images->render(); 
	 * Renders a unordered list of the images. 
	 *
	 * This is intended primarily as a handy tool when debugging or during development. 
	 *
	 * @return string rendered markup
	 *
	 */
	public function renderPageImages($event) {
		$images = $event->object; 
		$out = "\n<ul class='PageImages'>";
		foreach($images as $image) {
			$out .= "\n\t<li><img src='{$image->url}' alt='{$image->description}' /></li>";	
		}
		$out .= "\n</ul>";
		$event->return = $out; 
	}

	/**
	 * Return a string with the rendered output of this Page's Fields as markup in a definition list.
	 *
	 * This is intended primarily as a handy tool when debugging or during development. 
	 *
	 * @return string rendered markup
	 *
	 */
	public function renderPageFields($event) {
	
		$page = $event->object; 	
		if(!count($page->fields)) return ''; 
		$cnt = 0; 

		foreach($page->fields as $field) {

			if($field->type instanceof FieldtypeFieldsetClose) {
				continue; 

			} else if($field->type instanceof FieldtypeFieldsetOpen) {
				$out .= "\n<h2>{$field->label}</h2>"; 
				continue; 

			} else if(!$cnt) {
				$out = "\n<dl class='PageFields'>";
			}

			$value = $page->get($field->name); 

			if($field->type instanceof FieldtypeCheckbox) $value = $value ? "Yes" : "No";
				else if($value instanceof Pageimages) $value = $value->render();
		
			if(is_object($value)) { 	
				if($value instanceof PageArray) $value = $value->render();
					else if($value instanceof Page) $value = $value->title; 
			}

			$out .= "\n\n\t<dt>{$field->label}</dt>" . 
				"\n\t<dd>$value</dd>";

			$cnt++; 
		}

		$out .= "\n</dl><!--/.renderPageFields-->";
		$event->return = $out; 
	}
}
