<?php

/**
 * ProcessWire Newlines to <br /> Textformatter
 *
 * Inserts <br /> tags automatically into newlines
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2015 by Ryan Cramer 
 * This file licensed under Mozilla Public License v2.0 http://mozilla.org/MPL/2.0/
 * 
 * https://processwire.com
 * 
 *
 */

class TextformatterNewlineBR extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'Newlines to XHTML Line Breaks', 
			'version' => 100, 
			'summary' => "Converts newlines to XHTML line break <br /> tags. ", 
		); 
	}

	public function format(&$str) {
		$str = nl2br(trim($str));
	}
}
