<?php

/**
 * ProcessWire Smartypants Textformatter
 *
 * See: http://daringfireball.net/projects/smartypants/ 
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2015 by Ryan Cramer 
 * This file licensed under Mozilla Public License v2.0 http://mozilla.org/MPL/2.0/
 * 
 * https://processwire.com
 *
 */

class TextformatterSmartypants extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'SmartyPants Typographer', 
			'version' => 152, 
			'summary' => "Smart typography for web sites, by Michel Fortin based on SmartyPants by John Gruber. If combined with Markdown, it should be applied AFTER Markdown.", 
			'url' => 'http://michelf.com/projects/php-smartypants/typographer/', 
		); 
	}

	public function format(&$str) {
		require_once(dirname(__FILE__) . "/smartypants.php"); 
		$str = SmartyPants($str); 
	}
}
