<?php

/**
 * ProcessWire Markdown Textformatter
 *
 * See: http://daringfireball.net/projects/markdown/
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class TextformatterMarkdownExtra extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'Markdown Extra',
			'version' => 140,
			'summary' => "Markdown extra lightweight markup language by Michel Fortin based on Markdown by John Gruber",
			'url' => "http://michelf.com/projects/php-markdown/extra/",
		); 
	}

	public function format(&$str) {
		require_once('Michelf/MarkdownExtra.inc.php'); 
		$str = Michelf\MarkdownExtra::defaultTransform($str); 
	}

}
