<?php

/**
 * ProcessWire Self Profile
 *
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessProfile extends Process implements ConfigurableModule {

	public static function getModuleInfo() {
		return array(
			'title' => __('User Profile', __FILE__), // getModuleInfo title          
			'summary' => __('Enables user to change their password, email address and other settings that you define.', __FILE__), // getModuleInfo summary 
			'version' => 100, 
			'permanent' => true, 
			'permission' => 'profile-edit',
			);
	}

	protected $user; 

	public function __construct() {
		$this->set('profileFields', array()); 
	}

	public function init() {
		return parent::init();
	}

	public function ___execute() {
		$this->user = $this->fuel('user'); 
		$this->setFuel('processHeadline', $this->_("Profile:") . ' ' . $this->user->name); // Primary Headline (precedes the username)
		$form = $this->buildForm();
		if($this->input->post->submit_save_profile) {
			$this->processInput($form); 
			$this->session->redirect("./"); 
		} else { 
			return $form->render();
		}
	}	

	/**
	 * Build the form fields for adding a page
	 *
	 */
	protected function buildForm() {

		$form = $this->modules->get('InputfieldForm');

		$form->attr('id', 'ProcessProfile'); 
		$form->attr('action', './'); 
		$form->attr('method', 'post'); 
		$form->attr('enctype', 'multipart/form-data');
		$form->attr('autocomplete', 'off'); 

		foreach($this->user->fields as $field) {
			if($field->name == 'roles' || !in_array($field->name, $this->profileFields)) continue; 
			$inputfield = $field->getInputfield($this->user);
			$inputfield->value = $this->user->get($field->name); 
			$form->add($inputfield); 
		}

		$field = $this->modules->get('InputfieldSubmit');
		$field->attr('id+name', 'submit_save_profile'); 
		$form->add($field); 

		return $form; 
	}

	/**
	 * Save the submitted page add form
	 *
	 */
	protected function processInput(Inputfield $form) {
		$form->processInput($this->input->post);
		if(count($form->getErrors())) {
			$this->error($this->_("Profile not saved")); 
			return;
		}
		foreach($this->user->fields as $field) {
			if($field->name == 'roles' || !in_array($field->name, $this->profileFields)) continue; 
			$this->user->set($field->name, $form->get($field->name)->value); 	
		}
		if($this->user->isChanged()) {
			$this->user->save();
			$this->message($this->_("Profile saved")); 
		}
	}

	static public function getModuleConfigInputfields(array $data) {

		$profileFields = isset($data['profileFields']) ? $data['profileFields'] : array();
		$fieldOptions = wire('templates')->get('user')->fieldgroup; 

		$inputfields = new InputfieldWrapper();
		$f = wire('modules')->get('InputfieldCheckboxes');
		$f->label = __("What fields can a user edit in their own profile?");
		$f->attr('id+name', 'profileFields');
		foreach($fieldOptions as $field) {
			if($field->name == 'roles') continue;
			$f->addOption($field->name); 
		}
		$f->attr('value', $profileFields);
		$inputfields->add($f);

		return $inputfields;
	}



}

