<?php

/**
 * An Inputfield for handling XHTML "submit" buttons
 *
 */
class InputfieldSubmit extends Inputfield {

	public static function getModuleInfo() {
		return array(
			'title' => __('Submit', __FILE__), // Module Title
			'summary' => __('Form submit button', __FILE__), // Module Summary
			'version' => 100,
			'permanent' => true, 
			);
	}

	public function init() {
		parent::init();
		$this->attr('type', 'submit'); 
		$this->attr('name', 'submit'); 
		$this->attr('value', $this->_('Submit')); // Standard submit button label
		$this->attr('class', 'ui-button ui-widget ui-state-default ui-corner-all'); 
		$this->skipLabel = Inputfield::skipLabelHeader; 
	}

	public function ___render() {
		$attrs  = $this->getAttributesString();
		$out = "\n<button $attrs><span class='ui-button-text'>" . $this->attr('value') . '</span></button>';
		return $out; 
	}

	public function ___processInput(WireInputData $input) {
		// submit buttons don't need to process any input
		return $this; 
	}
	
}
