<?php

/**
 * ProcessWire Page Table Inputfield
 *
 * Concept by Antti Peisa
 * Code by Ryan Cramer
 * Sponsored by Avoine
 *
 * ProcessWire 2.x 
 * Copyright (C) 2014 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 *
 */

class InputfieldPageTable extends Inputfield {

	public static function getModuleInfo() {
		return array(
			'title' => __('ProFields: Page Table', __FILE__), // Module Title
			'summary' => __('Inputfield to accompany FieldtypePageTable', __FILE__), // Module Summary
			'version' => 4,
			'requires' => 'FieldtypePageTable'
			);
	}

	/**
	 * Labels for native fields, indexed by native field name
	 * 
	 * @var array
	 * 
	 */
	protected $nativeLabels = array();

	/**
	 * Initialize and establish default values
	 * 
	 */
	public function init() {

		// fieldtype and inputfield config settings
		$this->set('parent_id', 0); 
		$this->set('template_id', 0); 
		$this->set('columns', ''); 
		$this->set('nameFormat', '');

		// local settings
		$this->nativeLabels = array(
			'id' => $this->_x('ID', 'th'), 
			'name' => $this->_x('Name', 'th'), 
			'created' => $this->_x('Created', 'th'), 
			'modified' => $this->_x('Modified', 'th'), 
			'modifiedUser' => $this->_x('Modified By', 'th'), 
			'createdUser' => $this->_x('Created By', 'th'), 
			'url' => $this->_x('URL', 'th'), 
			'path' => $this->_x('Path', 'th'), 
			'template' => $this->_x('Template', 'th'), 
			'parent' => $this->_x('Parent', 'th'), 
			'numChildren' => $this->_x('Children', 'th'), 
			'status' => $this->_x('Status', 'th'), 
			);

		return parent::init();
	}

	/**
	 * Render the PageTable Inputfield
	 * 
	 * @return string
	 * 
	 */
	public function ___render() {

		// make sure we've got enough info to generate a table
		$errors = array();
		if(!$this->template_id) $errors[] = $this->_('Please configure this field with a template selection before using it.');
		if(!$this->columns) $errors[] = $this->_('Please enter one or more columns in your field settings before using this field.'); 
		if(count($errors)) return "<p class='ui-state-error'>" . implode('<br />', $errors) . "</p>";

		// determine what columns we'll show in the table
		$columnsString = $this->columns ? $this->columns : $this->getConfigDefaultColumns();
		$columns = array();	
		foreach(explode("\n", $columnsString) as $column) {
			$width = 0; 
			if(strpos($column, '=') !== false) list($column, $width) = explode('=', $column); 
			$column = trim($column); 
			$width = (int) $width; 
			$columns[$column] = $width; 
		}

		// render the table
		$out = $this->renderTable($columns); 

		// render an 'Add New' button
		$button = $this->wire('modules')->get('InputfieldButton'); 
		$editID = (int) $this->wire('input')->get('id'); 
		$parentID = $this->parent_id ? $this->parent_id : $editID;
		$button->icon = 'plus-circle';
		$button->value = $this->_x('Add New', 'button'); 

		$url = "../add/?modal=1&template_id=$this->template_id&parent_id=$parentID";
		if($this->nameFormat) $url .= "&name_format=" . $this->wire('sanitizer')->entities($this->nameFormat);
		$out .= "<div class='InputfieldPageTableAdd' data-url='$url'>" . $button->render() . "</div>";

		if(!$this->wire('config')->ajax) { 
			$url = "./?id=$editID&InputfieldPageTableField=$this->name"; 
			$out = "<div class='InputfieldPageTableContainer' data-url='$url'>$out</div>";
			// input for sorting purposes
			$value = $this->wire('sanitizer')->entities($this->attr('value')); 
			$name = $this->wire('sanitizer')->entities($this->attr('name')); 
			$out .= "<input type='hidden' name='$name' class='InputfieldPageTableSort' value='$value' />";
			$out .= "<input type='hidden' name='{$name}__delete' class='InputfieldPageTableDelete' value='' />";
		}

		return $out; 

	}

	/**
	 * Render the outputted PageTable <table> 
	 * 
	 * @param array $columns Array of column name => width percent
	 * @return string
	 * 
	 */
	protected function ___renderTable(array $columns) {

		$value = $this->attr('value'); 
		if(!count($value)) return ''; // if nothing in the value, just return blank
		$this->wire('modules')->get('MarkupAdminDataTable'); // for styles
		$language = $this->wire('languages') ? $this->wire('user')->language : '';
		$template = $this->template_id ? $this->wire('templates')->get((int) $this->template_id) : null;
		$fields = array();
		$labels = array();

		// populate $fields and $labels
		foreach($columns as $column => $width) {

			$field = null;
			$fieldName = $column; 
			$label = '';

			// check if field contains field.subfield
			if(strpos($column, '.') !== false) {
				$parentField = null;
				list($parentFieldName, $fieldName) = explode('.', $column); 

				if($template) $parentField = $template->fieldgroup->getFieldContext($parentFieldName); 
				if(!$parentField) $parentField = $this->wire('fields')->get($parentFieldName); 

				if($parentField) {
					$label = $parentField->get("label$language|label|name"); 

				} else if(isset($this->nativeLabels[$parentFieldName])) {
					$label = $this->nativeLabels[$parentFieldName]; 

				} else {
					$label = $parentFieldName; 
				}

				$label .= " > ";
			}

			if($template) $field = $template->fieldgroup->getFieldContext($fieldName); 
			if(!$field) $field = $this->wire('fields')->get($fieldName); 	

			if($field) {
				$label .= $field->get("label$language|label|name"); 
				$fields[$column] = $field; 

			} else if(isset($this->nativeLabels[$fieldName])) { 
				$label .= $this->nativeLabels[$fieldName]; 

			} else {
				$label .= $column; 
			}

			$labels[$column] = $label;
		}

		$out = $this->renderTableHead($columns, $labels) . $this->renderTableBody($value, $columns, $fields); 

		return $out; 		
	}

	/**
	 * Render the table head, from <table> to </thead>
	 * 
	 * @param array $columns
	 * @param array $labels
	 * @return string
	 * 
	 */
	protected function renderTableHead(array $columns, array $labels) {

		$out = "<table class='AdminDataTable AdminDataList'><thead><tr>";

		foreach($columns as $column => $width) {
			$attr = $width ? " style='width: $width%'" : '';
			$label = $labels[$column];
			$out .= "<th$attr>" . $this->wire('sanitizer')->entities($label) . "</th>";
		}

		$out .= "<th>&nbsp;</th></tr></thead>";

		return $out; 
	}

	/**
	 * Render the table body, from <tbody> to </table>
	 * 
	 * @param PageArray $items
	 * @param array $columns
	 * @param array $fields
	 * @return string
	 * 
	 */
	protected function renderTableBody(PageArray $items, array $columns, array $fields) {
		$out = "<tbody>";

		foreach($items as $item) {
			$of = $item->of();
			$item->of(true); 
			$out .= $this->renderTableRow($item, $columns, $fields); 
			$item->of($of); 
		}

		$out .= "</tbody></table>";
		return $out; 
	}

	/**
	 * Render an individual table row <tr> for a given PageTable item
	 * 
	 * @param Page $item
	 * @param array $columns
	 * @param array $fields
	 * @return string
	 * 
	 */
	protected function renderTableRow(Page $item, array $columns, array $fields) {

		$out = '';
		$n = 0;

		foreach($columns as $column => $width) {
			if(!$n) $column .= "|name"; // in case first/link field was not populated, use name as a backup
			$url = $n++ ? "" : "./?id=$item->id&modal=1";
			$out .= $this->renderTableCol($item, $fields, $column, $width, $url); 
		}

		// append a delete column/link
		$out .= "<td><a class='InputfieldPageTableDelete' href='#'><i class='fa fa-trash-o'></i></a></td>";

		// wrap the row in a <tr>
		$class = '';
		if($item->is(Page::statusUnpublished)) $class .= 'PageListStatusUnpublished ';
		if($item->is(Page::statusHidden)) $class .= 'PageListStatusHidden ';
		if($item->isTrash()) $class .= 'PageListStatusTrash';
		if($class) $class = " class='" . trim($class) . "'";

		return "<tr data-id='$item->id'$class>$out</tr>";	
	}

	/**
	 * Render an individual <td> for a table row 
	 * 
	 * @param Page $item
	 * @param array $fields
	 * @param $column
	 * @param $width
	 * @param string $linkURL
	 * @return string
	 * 
	 */
	protected function renderTableCol(Page $item, array $fields, $column, $width, $linkURL = '') {
		$out = $this->getItemValue($item, $fields, $column); 
		if($linkURL) $out = "<a class='InputfieldPageTableEdit' data-url='$linkURL' href='#'>$out</a>";
		$attr = $width ? " style='width: $width%'" : '';
		return "<td$attr>$out</td>";
	}

	/**
	 * Get the value for the given Page field identified by $column
	 * 
	 * @param Page $item
	 * @param array $fields
	 * @param $column
	 * @return mixed|object|string
	 * 
	 */
	protected function getItemValue(Page $item, array $fields, $column) {

		$fieldName = $column;
		$subfieldName = '';
		if(strpos($column, '.') !== false) list($fieldName, $subfieldName) = explode('.', $column); 

		if(isset($fields[$column])) {
			// custom
			$field = $fields[$column]; 
			$v = $item->getUnformatted($fieldName); 

			if(is_object($v) && $subfieldName) {
				// render it ourselves
				$value = $this->objectToString($v, $subfieldName); 
			} else {
				// let an inputfield's renderValue method handle it
				$in = $field->getInputfield($item); 
				$in->attr('value', $v); 
				$value = $in->renderValue();
			}

		} else {
			// native
			$value = $item->get($fieldName); 
			if(is_object($value) && $subfieldName) {
				$value = $this->objectToString($value, $subfieldName); 
				$fieldName = $subfieldName; 
			}
			if($fieldName == 'modified' || $fieldName == 'created') {
				$value = date($this->_('Y-m-d H:i'), (int) $value); // Date format for created/modified
			}
		}

		return $value; 
	}

	/**
	 * Convert an object to a string for rendering in a table
	 * 
	 * @param $object
	 * @param string $property Property to display from the object (default=title|name)
	 * @return string
	 * 
	 */
	protected function objectToString($object, $property = '') {

		if($object instanceof WireArray) {
			if(!$property) $property = 'title|name';
			$value = $object->implode("\n", $property); 

		} else if($property) {
			$value = $object->$property; 
			if(is_object($value)) $value = $this->objectToString($value); 
		} else {
			$value = (string) $value; 
		}

		$value = $this->wire('sanitizer')->entities(strip_tags($value)); 
		$value = nl2br($value); 
		return $value; 
	}

	/**
	 * Process input submitted to a PageTable Inputfield
	 * 
	 * @param WireInputData $input
	 * @return $this
	 * 
	 */
	public function ___processInput(WireInputData $input) {

		$name = $this->attr('name'); 
		$deleteName = $name . '__delete';

		$deleteIDs = explode('|', $input->$deleteName); 
		$ids = explode('|', $input->$name); 
		$value = $this->attr('value'); 
		$sorted = new PageArray();	

		// trash items that have been deleted
		foreach($deleteIDs as $id) {
			foreach($value as $item) {
				if($id != $item->id) continue; 
				if(!$item->deleteable()) continue; 
				$this->wire('pages')->trash($item); 	
				$value->remove($item); 
			}
		}

		foreach($ids as $id) {
			if(in_array($id, $deleteIDs)) continue; 
			foreach($value as $item) {
				if($id == $item->id) $sorted->add($item); 
			}
		}

		// add in new items that may have been added after a sort
		foreach($value as $item) { 
			if(!in_array($item->id, $ids)) $sorted->add($item); 
		}

		if("$value" != "$sorted") {
			$this->setAttribute('value', $sorted); 
			$this->trackChange('value'); 
		}

		return $this; 
	}

	/**
	 * Set an attribute to the Inputfield
	 *
	 * In this case we capture set to the 'value' attribute to make sure it can only be a PageArray
	 * 
	 * @param array|string $key
	 * @param int|string $value
	 * @return $this
	 * @throws WireException
	 * 
	 */
	public function setAttribute($key, $value) {
		if($key == 'value') {
			if($value === null) $value = new PageArray();
			if(!$value instanceof PageArray) throw new WireException('This Inputfield only accepts a PageArray for its value attribute.'); 
		}
		return parent::setAttribute($key, $value); 
	}

	/**
	 * Determine a default set of columns for the PageTable based on the fields defined in the defined template
	 * 
	 * @return string of newline separated field names
	 * 
	 */
	protected function getConfigDefaultColumns() {
		$out = '';
		if(!$this->template_id) return $out;
		$template = $this->wire('templates')->get((int) $this->template_id); 
		if(!$template) return $out;
		$n = 0;
		foreach($template->fieldgroup as $field) {
			$out .= $field->name . "\n";	
			if(++$n >= 5) break;
		}
		return trim($out); 
	}

	/**
	 * Get field configuration for input tab
	 * 
	 * @return InputfieldWrapper
	 * 
	 */
	public function ___getConfigInputfields() {
		$inputfields = parent::___getConfigInputfields(); 

		$f = $this->wire('modules')->get('InputfieldTextarea'); 
		$f->attr('name', 'columns'); 
		$f->label = $this->_('Table fields to display in admin'); 
		$f->description = $this->_('Enter the names of the fields (1 per line) that you want to display as columns in the table. To specify a column width for the field, specify "field_name=30" where "30" is the width (in percent) of the column. When specifying widths, make the total of all columns add up to 100.');  // Columns description
		$f->notes = $this->_('You may specify any native or custom field. You may also use subfields (field.subfield) with fields that contain multiple properties, like page references.') . ' '; // Columns notes
		$columns = $this->columns ? $this->columns : $this->getConfigDefaultColumns();
		$f->attr('value', $columns); 

		$template = $this->template_id ? $this->wire('templates')->get((int) $this->template_id) : null;

		if($template) {
			$options = array();
			foreach($template->fieldgroup as $item) $options[$item->name] = $item->name; 
			$f->notes .= $this->_('Custom fields assigned to your selected template include the following:') . ' **';
			$f->notes .= implode(', ', $options) . '**';
		} else {
			$f->notes .= $this->_('To see a list of possible custom fields here, select a template on the Details tab, Save, and come back here.'); 
		}

		$inputfields->add($f); 

		$f = $this->wire('modules')->get('InputfieldText');
		$f->attr('name', 'nameFormat');
		$f->attr('value', $this->nameFormat);
		$f->label = $this->_('Automatic Page Name Format');
		$f->description = $this->_('When populated, pages will be created automatically using this name format whenever a user clicks the "Add New" button. If left blank, the user will be asked to enter a name for the page before it is created.'); // page name format description
		$f->notes = $this->_('If the name format contains any non-alphanumeric characters, it is considered to be a [PHP date](http://www.php.net/manual/en/function.date.php) format. If it contains only alphanumeric characters then it will be used directly, with a number appended to the end (when necessary) to ensure uniqueness.'); // page name format notes
		$f->notes .= ' ' . $this->_('Example: **Ymd:His** is a good name format for date/time based page names.'); 
		$f->collapsed = Inputfield::collapsedBlank;
		$inputfields->add($f);

		return $inputfields; 
	}
}
