<?php

class JqueryUI extends ModuleJS { 

	public static function getModuleInfo() {
		return array(
			'title' => 'jQuery UI',
			'version' => 194,
			'summary' => 'jQuery UI as required by ProcessWire and plugins',
			'href' => 'http://ui.jquery.com', 
			'permanent' => true, 
		);
	}
	
	public function __construct() {
		$this->addComponents(array(
			'modal' => 'modal.js',
			'touch' => 'touch.js' 
			));
	}
	
	public function init() {
		parent::init();
		if($this->wire('session')->touch) $this->use('touch'); 
	}


}
