<?php

class JqueryUI extends ModuleJS { 

        public static function getModuleInfo() {
                return array(
                        'title' => 'jQuery UI',
                        'version' => 192,
                        'summary' => 'jQuery UI as required by ProcessWire and plugins',
			'href' => 'http://ui.jquery.com', 
			'permanent' => true, 
                        );
        }

	// note ModuleJS automatically loads any JS or CSS files with the same basename as this module

}
