<?php

require_once(dirname(__FILE__) . '/FieldtypeTextLanguage.module'); 

class FieldtypePageTitleLanguage extends FieldtypeTextLanguage implements FieldtypePageTitleCompatible {

	public static function getModuleInfo() {
		return array(
			'title' => 'Page Title (Multi-language)',
			'version' => 100,
			'summary' => 'Field that stores a page title in multiple languages',
			'permanent' => false,
			);
	}

        public function getInputfieldClassName() {
		return 'InputfieldPageTitle';
	}

        public function isAdvanced() {
                //return true;
		return false;
        }

        public function ___getCompatibleFieldtypes(Field $field) {
                $fieldtypes = new Fieldtypes();
                foreach($this->fuel('fieldtypes') as $fieldtype) {
                        if($fieldtype instanceof FieldtypePageTitleCompatible) $fieldtypes->add($fieldtype);
                }
                return $fieldtypes;
        }

	public function ___install() {
		throw new WireException("This fieldtype is not yet ready for installation. Remove this line from the installer if you want to install anyway."); 
	}

}
